INSERT INTO Profession VALUES
(0, "miscellaneous", "The profession is miscellaneous.")
,(1, "soundtrack", "The profession is soundtrack.")
,(2, "actor", "The profession is actor.")
,(3, "actress", "The profession is actress.")
,(4, "music_department", "The profession is music department.")
,(5, "writer", "The profession is writer.")
,(6, "director", "The profession is director.")
,(7, "producer", "The profession is producer.")
,(8, "make_up_department", "The profession is make-up department.")
,(9, "composer", "The profession is composer.")
,(10, "assistant_director", "The profession is assistant director.")
,(11, "camera_department", "The profession is camera department.")
,(12, "editor", "The profession is editor.")
,(13, "cinematographer", "The profession is cinematographer.")
,(14, "casting_director", "The profession is casting_director.")
,(15, "script_department", "The profession is script_department.")
,(16, "art_director", "The profession is art_director.")
,(17, "stunts", "The profession is stunts.")
,(18, "editorial_department", "The profession is editorial department.")
,(19, "costume_department", "The profession is costume department.")
,(20, "animation_department", "The profession is animation department.")
,(21, "art_department", "The profession is art department.")
,(22, "executive", "The profession is executive.")
,(23, "special_effects", "The profession is special effects.")
,(24, "production_designer", "The profession is production designer.")
,(25, "production_manager", "The profession is production manager.")
,(26, "sound_department", "The profession is sound department.")
,(27, "talent_agent", "The profession is talent agent.")
,(28, "casting_department", "The profession is casting department.")
,(29, "costume_designer", "The profession is costume designer.")
,(30, "visual_effects", "The profession is visual effects.")
,(31, "location_management", "The profession is location management.")
,(32, "set_decorator", "The profession is set decorator.")
,(33, "transportation_department", "The profession is transportation department.")
,(34, "manager", "The profession is manager.")
,(35, "legal", "The profession is legal.")
,(36, "publicist", "The profession is publicist.")
,(37, "assistant", "The profession is assistant.")
,(38, "production_department", "The profession is production department.")
,(39, "electrical_department", "The profession is electrical department.")
,(40, "choreographer", "The profession is choreographer.")
;
